### ISSUE TITLE
Train our own dataset

### ISSUE THREAD

**Issue by Miraclerice** [Junelin2333/LanGuideMedSeg-MICCAI2023#4]
If I want to train my own dataset, but the input is an RGB image, where do I need to modify it so that the number of channels corresponds?If you have a solution for this, I would appreciate it! @Junelin2333

**Comment by Junelin2333** [comment]
Sry I forgot to reply in time. If you want to train on RGB image, you don't even need to change any code. My code is running on images in 3 channels.

See _`utils/model.py/LanGuideMedSeg/forward`_:
```
        if image.shape[1] == 1:   
            image = repeat(image,'b 1 h w -> b c h w',c=3)
```
